version: '2'
services:
  web:
    build: .
    command: gunicorn app:app --chdir kingler -k eventlet -w 1 -b 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - db
  db:
    image: mongo:3.4.1